comments

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,7 +66,8 @@ jobs:
           PGPASSWORD: secret
         # use the username and database name we set in the service above.
         run: |
-          set -xe
+          set -x # show the commands
+          set -e # fail the step if one statement fails
           echo "SELECT CURRENT_TIME" | psql -h mypg -U myusername $POSTGRES_DB
           echo "SELECT version()" | psql -h mypg -U myusername mydb
           echo "CREATE TABLE counter (name text, cnt int)" | psql -h mypg -U myusername mydb
